### ISSUE TITLE
404 on examples website docs

### ISSUE THREAD

**Issue by ppikachu** [Tresjs/cientos#102]
### Describe the bug

Clicking on examples lands on 404 page not found.

### Reproduction

https://cientos.tresjs.org/examples.html

### Used Package Manager

npm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/Tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by alvarosabu** [comment]
Hey @ppikachu @JaimeTorrealba just fixed it on #104
