### ISSUE TITLE
Sky

### ISSUE THREAD

**Issue by JaimeTorrealba** [Tresjs/cientos#106]
### Description

For more options on outside environment

### Suggested solution

https://github.com/pmndrs/drei#sky

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.

**Comment by andretchen0** [comment]
If no one else is assigned in the meantime, I'll start working on this once `SVG` and `Lensflare` are finished.

**Comment by JaimeTorrealba** [comment]
Thanks, @andretchen0 :)

We will add you to the organization, so everything will be easier
