### ISSUE TITLE
Refactor useCientos to new state context provider

### ISSUE THREAD

**Issue by alvarosabu** [Tresjs/cientos#120]
### Description

Adapt `cientos` package to https://github.com/Tresjs/tres/issues/331 changes

#### Abstractions

- [x] Environment
- [x] MouseParallax
- [x] Stars
- [x] Smoke
- [x] Levioso
- [x] Contact Shadows
- [x] Precipitation

#### Controls
- [x] OrbitControls @alvarosabu 
- [x] TransformControls
- [x] PointerLockControls
- [x] KeyboardControls
- [x] MapControls
- [x] ScrollControls

### Materials

- [x] WobbleMaterial

### Staging

- [x] Backdrop

### Misc

- [x] useTweakpane

### Suggested solution

- [x] Refactor watchers 
- [x] Remove deconstruct props if needed
- [x] Merge to 'next'

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.

**Comment by JaimeTorrealba** [comment]
@alvarosabu I don't see changes related to the new state in stars and precipitation.

Can we mark them as ready?

**Comment by alvarosabu** [comment]
What do you mean @JaimeTorrealba I had not worked on them yet, have you?

**Comment by JaimeTorrealba** [comment]
@alvarosabu they don't use useCientos or any context related
