### ISSUE TITLE
ScrollControls props are not reactive

### ISSUE THREAD

**Issue by alvarosabu** [Tresjs/cientos#131]
### Describe the bug

I'm trying to change the direction of the scrolling to horizontal when `progress > 0.5`  like this:

```ts
  <ScrollControls ref="scRef" 
      v-model="progress"
      :distance="10"
      :smooth-scroll="0.1"
      html-scroll
      :horizontal="progress > 0.5"
  >
  ```
  
  but props are not reactive

### Reproduction

https://stackblitz.com/edit/stackblitz-starters-jq66po?file=src%2Fcomponents%2FTheExperience.vue

### Steps to reproduce

Scroll until the point that horizontal should be true

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.6.3 - /usr/local/bin/pnpm
  npmPackages:
    @tresjs/cientos: 2.3.0 => 2.3.0 
    @tresjs/core: 2.4.0 => 2.4.0 
    vite: ^4.4.3 => 4.4.3
```

### Used Package Manager

pnpm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/Tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by JaimeTorrealba** [comment]
As is in the Docs, for now you can't use html-scroll with horizontal scroll, that should be a enchanment.

Right now, somethig like that will break completely the progress, so that is not possible for now

But yeah now is not reactive, we need to discuss how can we make it reactive without breaking the progress indicator
