### ISSUE TITLE
Enhance Environment and useEnvironment abstractions

### ISSUE THREAD

**Issue by alvarosabu** [Tresjs/cientos#147]
### Description

As a developer using TresJS, I want 
- Environment props to be reactive
- More presets other than 'sunset' (city, etc)

 so that:
- I can dynamically configure the preset or toggle the `background` property

### Suggested solution

Modify the `useEnvironment/component.ts` component so:

- Convert to vue file SFC
-  texture should be a ref
- Set the default for the props here.

Modify the `useEnvironment/index.ts` composable so:

- Reacts to prop changes (Using watchers and computed)
- Return the texture as a ref

 

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.

**Comment by garrlker** [comment]
I can take a crack at this!

**Comment by alvarosabu** [comment]
Awesome @garrlker let me know if you need help

**Comment by garrlker** [comment]
Is there a certain way I'm supposed to pnpm link the playground project to cientos?

Every which way I try gives me an error like
```bash
 playground  pnpm i
Already up to date
Progress: resolved 933, reused 891, downloaded 0, added 0, done

> @tresjs/playground@ postinstall /Users/garrlker/Programming/vue/playground
> nuxt prepare

Nuxi 3.6.2                                                                          5:05:39 PM

[5:05:40 PM]  ERROR  ENOENT: no such file or directory, open '/Users/garrlker/Programming/vue/playground/@tresjs/cientos'
```

Feels like I'm missing something basic

**Comment by alvarosabu** [comment]
Hey there @garrlker the playground you mention the playground inside of cientos or [@tresjs/playground](https://github.com/Tresjs/playground) ? 

If it's the second is a completely different project and repo. To test cientos you can run `npm run playground`

**Comment by garrlker** [comment]
Oh! I thought it was `@tresjs/playground` and needed to npm link.
Whoops, I need to RTFM.

Thanks @alvarosabu!
