### ISSUE TITLE
useFBO abstraction

### ISSUE THREAD

**Issue by alvarosabu** [Tresjs/cientos#149]
### Description

As a Developer using TresJS I would like to have a composable `useFBO` that leverages the effort of creating a `THREE.WebGLRenderTarget` 

```
const target = useFBO({ stencilBuffer: false })

```

Drei's
https://github.com/pmndrs/drei/blob/master/src/core/useFBO.tsx

Reference:
https://github.com/pmndrs/drei/tree/master#usefbo

### Suggested solution

Implement a composable that accepts:

- `width`
- `height`/
- `samples`   // Defines the count of MSAA samples. Can only be used with WebGL 2. Default: 0 
- `depth` // If set, the scene depth will be rendered into buffer.depthTexture. Default: false

And returns the renderTarget, The rendertarget should be automatically disposed when unmounted.

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.

**Comment by kekkorider** [comment]
Any update on this? 🙂

**Comment by JaimeTorrealba** [comment]
@kekkorider Would you like to take this?

**Comment by JaimeTorrealba** [comment]
@kekkorider fantastic! 
We're here to help, so please feel free to contact me in discord (Io anche parlo italiano) or Alvaro
