### ISSUE TITLE
svg component

### ISSUE THREAD

**Issue by JaimeTorrealba** [Tresjs/cientos#155]
### Description

A wrapper around THREE.SVG loader

### Suggested solution

Something similar to https://github.com/pmndrs/drei#svg

A component like <Svg src={urlOrRawSvgString} />

### Alternative

Any other alternative is valid

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.

**Comment by andretchen0** [comment]
I'll work on this if you'd like to assign me.

**Comment by andretchen0** [comment]
@JaimeTorrealba 

* The drei version of `Svg` takes some optional props. Among them are `fillMeshProps` and `strokeMeshProps`, whose attributes are copied to the fill meshes and stroke meshes, respectively. Are those desired here?
* Do we want both an `<SVG>` component and a `useSVG()` function? Similar to `<GLTFModel>` and `useGLTF`.

**Comment by JaimeTorrealba** [comment]
Hi @andretchen0 

1. I would say yes, even I can't think of specific use cases right now
2. What do you think? 
In the case of useGLTL we have much more flexibility, we can destructure what we want and do operations with it before attach them to the primitive

What would be the possible use Cases of useSVG()

**Comment by andretchen0** [comment]
> I would say yes, even I can't think of specific use cases right now

Ok. I can't think of one either, but I'll put them in.

> What would be the possible use Cases of useSVG()

In isolation, I don't really see one. To me, it only makes sense in that it would match the other loaders, e.g.:

* `useGLTF([...])`
* `<GLTFModel [...] />`

* `useSVG([...])`
* `<SVG [...] />`

But `useGLTF` returns 

```
{
 animations: Array<THREE.AnimationClip>
 nodes: Array<Object3D>
 materials: Array<THREE.Material>
 scene: THREE.Scene
}
```

Of those, `useSVG` could potentially return `{nodes, materials}`, but I can't think of a use case.

For the time being, I won't expose `useSVG`.

**Comment by JaimeTorrealba** [comment]
Ok, let's no add extra complexity, if we need the useSVG we'll add in the future.

So don't worry and add just the <svg /> component for now :)

**Comment by andretchen0** [comment]
[Draft PR here](https://github.com/Tresjs/cientos/pull/187)
