### ISSUE TITLE
stats

### ISSUE THREAD

**Issue by JaimeTorrealba** [Tresjs/cientos#158]
### Description

Add a component stats, to measure the performance of the scene

### Suggested solution

See https://github.com/pmndrs/drei#stats

### Alternative

statsGI

### Additional context

When finish this component add a new issue to add statsGI

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.

**Comment by damienmontastier** [comment]
Hey ! [stats-gl](https://github.com/RenaudRohlinger/stats-gl) is now available, I haven't used it for any projects yet, but it looks cool!
