### ISSUE TITLE
Investigation, delete value.value to access some components

### ISSUE THREAD

**Issue by JaimeTorrealba** [Tresjs/cientos#160]
### Description

Currently some abstraction in cientos, need to be access by value.value at the moment of reference them

As a good DX we need to find a solution to this detail.

The problem is located in the EJ:

defineExpose({
  value: starsRef,
})

### Suggested solution

If you have a good solution, please explain it here

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.

**Comment by JaimeTorrealba** [comment]
@alvarosabu Your appreciation here will be highly valuable too.

As far I can see, we could standardize this one with other word, like "current" or "instance". Having another point of view will be fantastic.

Or we could just leave as it is.

Of course no rush

**Comment by alvarosabu** [comment]
I completely agree @JaimeTorrealba , what about `ref` since is a reference of the instance, or well `instance` is ok to, whatever is shorter for the chaining `boxRef.ref.value` 

We would need to replace:

```ts
defineExpose({
  value: controlsRef,
})
```

With

```ts
defineExpose({
  ref: controlsRef,
})
```

**Comment by JaimeTorrealba** [comment]
In that case will be boxRef.value.ref, but yeah I like it

**Comment by andretchen0** [comment]
Hey @JaimeTorrealba @alvarosabu ,

> How do you feel about this? Are you comfortable with the value.value pattern? Do you have any problems with it? I personally don't like it, but my solutions also don't convince me 😮‍💨

I agree. I would like to change `value.value`.

## Idea 1

For Cientos, we're mostly just exposing the root `Object3D`. What do you guys think of this?

```vue
<script setup>
// ...
// NOTE: the Object3D that will serve as the root for this component
const obj = new Object3D();
defineExpose(obj)
</script>
```

In the parent, it's used like this:

```vue
<script setup>
// ...
const levioso = ref(null)
const box = ref(null)
watch(levioso, () => console.log(levioso.value.isObject3D))
watch(box, () => console.log(box.value.isObject3D))
</script>

<template>
<Levioso ref="levioso">
    <Box ref="box" />
</Levioso>
</template>
```

## Idea 2

Otherwise, if we want to leave room for exposing other fields, maybe ... :

```js
defineExpose({
    root:obj,
    someUsefulFunction
})
```

... which gives us ... :

```js
watch(levioso, () => console.log(levioso.value.root.isObject3D))
```

I think many/most Vue/Three users will understand "root" (as in "root node of the child") without need for further explanation. And "root" couples nicely with digging down into the subtree:

```js
levioso.value.root.children
```

We'd need to figure out other names for e.g., what's in `defineExpose` from `useFBO`.

**Comment by alvarosabu** [comment]
Hi, @andretchen0 I remember we added the `.value` to the expose because you can't pass ref or reactive, only plain objects. dunno if it's still a restriction.

I like the second idea.

**Comment by andretchen0** [comment]
> I remember we added the `.value` to the expose because you can't pass ref or reactive, only plain objects. dunno if it's still a restriction.

Sure thing. As of today, [passing plain values or refs is documented]( https://vuejs.org/api/sfc-script-setup.html#defineexpose).

**Comment by alvarosabu** [comment]
Let's do it. @JaimeTorrealba please create a todo list of all the components that need change on the ticket and let's go for it.


Since this will be a breaking change, please open the branch from `v4`

**Comment by JaimeTorrealba** [comment]
Perfect. Let's stick with "root" as Andre points, we could expose more than one instance (method, etc).

Wait a PR soon ...
