### ISSUE TITLE
Tweakpane as peer dep

### ISSUE THREAD

**Issue by alvarosabu** [Tresjs/cientos#168]
### Description

As a developer using cientos, I would like to have the minimal bundle possible.

Atm, the bundle size of cientos is around 600 Kb which is huge, at least 300kb (31%) are coming from [TweakPane](https://cocopon.github.io/tweakpane/)

<img width="1479" alt="Screenshot 2023-08-13 at 12 37 22" src="https://github.com/Tresjs/cientos/assets/4699008/9062618d-f7ac-4aad-9b20-9631e4bd2623">

<img width="631" alt="Screenshot 2023-08-13 at 12 38 50" src="https://github.com/Tresjs/cientos/assets/4699008/e4dc5dd6-c344-41b7-bee5-392fc075bbf3">

### Suggested solution

Take out tweakpane from the final bundle by making it a peer dep

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.

**Comment by gimyboya** [comment]
When using this with Nuxt i am getting `Could not resolve "tweakpane"` Error
<img width="1035" alt="image" src="https://github.com/Tresjs/cientos/assets/14952013/7dfaebaa-83f9-4b1a-a9fe-fab3965a24e8">

**Comment by alvarosabu** [comment]
You have to install `tweakpane`. We are gonna deprecate `useTweakpane` soon.
