### ISSUE TITLE
LensFlare

### ISSUE THREAD

**Issue by JaimeTorrealba** [Tresjs/cientos#171]
### Description

As a developer using Tresjs I would like to use lensFlare easily

### Suggested solution

Create an abstraction of the ThreeJs addons [Lensflare](https://threejs.org/docs/index.html#examples/en/objects/Lensflare)

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.

**Comment by andretchen0** [comment]
@JaimeTorrealba 

I'll take a crack at it.

**Comment by JaimeTorrealba** [comment]
@andretchen0 assigned my friend.

Thanks and any question, we're here to help

**Comment by andretchen0** [comment]
## Visuals

Here's what I've got at the moment, visually. How's that looking?

https://github.com/Tresjs/cientos/assets/20469369/c932eb8b-9564-4e06-8923-4bf89b2696b5


----

## Textures

I'm not sure about the best approach for the default textures.

Users can supply their own textures, but I'd prefer to include some sensible defaults.

There are textures in the Three.js repository. But they're licensed as [CC non-commercial](https://github.com/mrdoob/three.js/blob/67d574bcda95fd50bc3477084eb9d092a3004d79/examples/textures/lensflare/LICENSE.txt#L4).

So, at the moment, I'm generating the textures in a canvas at runtime. It's about 150 lines of TS – over half of the LOC in the component. Is that ok, or would you prefer using image textures?

**Comment by JaimeTorrealba** [comment]
Hi @andretchen0 it looks amazing, I love it

For the texture, I recommend that you use image texture, and set it as a default.

You can look at the [smoke](https://github.com/Tresjs/cientos/blob/main/src/core/abstractions/Smoke.vue) element as a reference. In that component, if you don't provide a specific texture, it uses one as default (that means you always have to use a suspense component, and wrap it, remember to add it to the docs)

To add a texture, it's necessary to make a PR to our (assets)[https://github.com/Tresjs/assets] repository. This is a special repository that contains all the assets for the abstraction/example components, (check the license before adding it) That way we can be sure that we always have the current resource

**Comment by andretchen0** [comment]
Hey @JaimeTorrealba, I wonder if I could get your feedback again.

To summarize: Would using a seedable pseudorandom number generator be useful/welcome here?

## The problem

Lens flares tend to look better if they have 10+ elements. In terms of THREE's Lensflare, the data required might look something like:

````
 <Lensflare :flare="[{ texture: circleBlurTexture, size: 366, distance: 0, color: 'white' },
  { texture: circleTexture, size: 155, distance: -0.3, color: 'gray' },
  { texture: starTexture, size: 512, distance: 0, color: 'gray' },
  { texture: lineTexture, size: 512, distance: 0, color: 'white' },
  { texture: ringTexture, size: 512, distance: 0, color: 'white' },
  { texture: circleTexture, size: 256, distance: 0.6, color: 'gray' },
  { texture: circleTexture, size: 80, distance: 0.7, color: 'gray' },
  { texture: circleBlurTexture, size: 70, distance: 0.9, color: 'white' },
  { texture: circleTexture, size: 65, distance: 1, color: 'white' },
  { texture: circleBlurTexture, size: 60, distance: 1.8, color: 'white' },
  { texture: circleTexture, size: 60, distance: 2.0, color: 'gray' },
  { texture: circleTexture, size: 155, distance: 2.3, color: 'gray' }]" />
````

That's not very easy for a user to specify on their own. And it's not very easy to modify.

## A possible solution

I was wondering if a seedable pseudorandom number generator would be welcome here. We could make the flare JSX look like this:

```
<Lensflare :seed="503" :flare="[{color: 'red'}, {color:'green'}, {color:'blue', distance:1.2}]" />
```

Here, the default flare elements would be generated based on `seed` – the same `seed` always produces the same flare defaults.

Then the `flare` option lets users override the defaults they don't like.

## Disadvantages

Extra code:

* pseudorandom generator/tools 
* pools of defaults for the generator tools to pick from

### Note

The seedable pseudorandom number generation and associated tools could be packaged into a class and made available to other modules. But I'm not sure if that's useful at this point.

Also, for what it's worth, THREE has `MathUtils.seededRandom()` but it doesn't contain tools for working with the generator.

**Comment by JaimeTorrealba** [comment]
Does your solution provide options to customize the look of the component using textures too?

I would also like to see your solution in code, can you update the PR (marked as draft please)

As general I like the Idea, :) I worry a little about the final options for custom effects in the component

**Comment by andretchen0** [comment]
@JaimeTorrealba

> I would also like to see your solution in code, can you update the PR (marked as draft please)

https://github.com/Tresjs/cientos/pull/185

Any feedback/advice is welcome. As is guidance for fixing the CI failures.
