### ISSUE TITLE
Could not resolve "@tweakpane/plugin-essentials" since at least Cientos 3.1.0

### ISSUE THREAD

**Issue by bperel** [Tresjs/cientos#179]
### Describe the bug

I am doing: `vite`
I expect: vite to load without error, like it did for cientos < 3
What is actually happening: 
```
  VITE v4.4.9  ready in 1502 ms

  ➜  Local:   http://127.0.0.1:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
Could not resolve "@tweakpane/plugin-essentials"

    node_modules/.pnpm/@tresjs+cientos@3.1.0_three@0.154.0_tweakpane@4.0.0_vue@3.3.4/node_modules/@tresjs/cientos/dist/trescientos.js:15:20:
      15 │ import * as xo from "@tweakpane/plugin-essentials";
         ╵                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@tweakpane/plugin-essentials" as external to exclude it from the bundle,
  which will remove this error.

 ELIFECYCLE  Command failed with exit code
```

### Reproduction

https://stackblitz.com/edit/tresjs-basic-hkgcpb?file=package.json

### Steps to reproduce

npm install && npm run dev

### Used Package Manager

npm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/Tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by alvarosabu** [comment]
Since v3.1.0 tweakpane and @tweakpane/plugin-essentials are not longer part of the bundle, they need to be installed as peer dep, just install the package

**Comment by bperel** [comment]
> Since v3.1.0 tweakpane and @tweakpane/plugin-essentials are not longer part of the bundle, they need to be installed as peer dep, just install the package

In that case should it be part of the installation documentation? In the Stackblitz I don't use Tweakpane so I didn't expect to need to install this dependency

**Comment by alvarosabu** [comment]
@bperel we are going to start deprecating useTweakpane from cientos, for now the fix above will prevent your code from breaking, you can continue by using `@tresjs/cientos@next` or waiting for the PR to be merged
