### ISSUE TITLE
Start migrating playground controls to @tresjs/leches

### ISSUE THREAD

**Issue by alvarosabu** [Tresjs/cientos#183]
### Description

Since we are going to deprecate `useTweakpane` soon, let's start migrating all the playground examples that use tweakpane with `@tresjs/leches` instead

### Suggested solution

Migrate:

- [x] ./playground/src/pages/staging/EnvironmentDemo.vue
- [x] ./playground/src/pages/materials/CustomShaderMaterialDemo.vue
- [x] ./playground/src/pages/staging/ContactShadowsDemo.vue
- [x] ./playground/src/pages/staging/StarsDemo.vue
- [x] ./playground/src/pages/staging/PrecipitationDemo.vue
- [x] ./playground/src/pages/controls/OrbitControlsDemo.vue
- [x] ./playground/src/pages/controls/TransformControlsDemo.vue
- [x] ./playground/src/pages/controls/CameraControlsDemo.vue
- [x] ./playground/src/pages/abstractions/LeviosoDemo.vue
- [x] ./playground/src/pages/abstractions/FBODemo.vue

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.

**Comment by andretchen0** [comment]
Are there docs for `leches`? Or a repo?

All I've managed to find so far is the [source on npm](https://www.npmjs.com/package/@tresjs/leches?activeTab=code).

**Comment by alvarosabu** [comment]
Hi @andretchen0 I just made it public https://github.com/Tresjs/leches 

The documentation can be found here https://tresleches.netlify.app/

**Comment by alvarosabu** [comment]
Hey @JaimeTorrealba @andretchen0  I just created a branch for this, I'm planning to migrate some of them to TresLeches but I really need your support here.

We need to deprecate tweakpane for v4.

**Comment by andretchen0** [comment]
> Hey @JaimeTorrealba @andretchen0 I just created a branch for this, I'm planning to migrate some of them to TresLeches but I really need your support here.

@alvarosabu 

Happy to help out!

The branch isn't linked in the sidebar here or on #296. **Can you add the link and then @ me?**

I'm guessing the preference is to use Leches where possible and not [v-tweakpane](https://github.com/vinayakkulkarni/v-tweakpane), which was linked on #296? Is that right?

**Comment by andretchen0** [comment]
> branch

Got it. Thanks!

> let me know which ones would you take

I'll start at the bottom of the "Migrate" list in the top-line issue and work up. 

I'll do my best to remember to push as the files are completed and tick the proper box in the "Migrate" list. 

Housekeeping: 

* I added the paths to the "Migrate" list on the top-line issue to (hopefully) reduce ambiguity. 
* I'm not sure which file(s) `TheGizmos` refers to.

**Comment by andretchen0** [comment]
@alvarosabu 

I've just pushed the last of the playground demos to #308 .

## Questions

* What should we do about "TheGizmos" in the top-level issue description? I'm not sure what that refers to. Could you let me know which files need to be changed or whether to ignore "TheGizmos"?
* There are still some non-playground occurences of `tweakpane` in Cientos. See list below. I've left them in place for now because this issue is "Start migrating playground controls". Do you want those to be addressed under this issue?
* Are we ready to review #308 ?

## Remaining occurences of `tweakpane`

```
package.json
pnpm-lock.yaml
vite.config.ts
docs/package.json
docs/.vitepress/config.ts
docs/.vitepress/theme/components/CustomShaderMaterialDemo.vue
docs/guide/misc/use-tweakpane.md
src/core/misc/index.ts
src/core/misc/useTweakPane/index.ts
```

**Comment by alvarosabu** [comment]
Hi buddy @andretchen0 , sorry that it took me so long to get back to you. 

Amazing job migrating all the demos to tresleches and for providing insightful feedback about the GUI controls.

 > What should we do about "TheGizmos" in the top-level issue description? I'm not sure what that refers to. Could you let me know which files need to be changed or whether to ignore "TheGizmos"?
 
 Ignore it, it was the old name of the TransformControlsDemo
 
 > There are still some non-playground occurences of tweakpane in Cientos. See list below. I've left them in place for now because this issue is "Start migrating playground controls". Do you want those to be addressed under this issue?
 
Lets include in this PR the ones in the docs, then we merge this because the removal of tweakpane is gonna be done in #296 

> Are we ready to review https://github.com/Tresjs/cientos/pull/308 ?

 Lets include the changes in the docs and we are ready
 
 Thanks a lot 🙏🏻
