### ISSUE TITLE
Global audio component

### ISSUE THREAD

**Issue by JaimeTorrealba** [Tresjs/cientos#209]
### Description

As a developer using Tresjs I would like to have a simple way to add a global sound.

### Suggested solution

An abstraction of: https://threejs.org/docs/index.html?q=audio#api/en/audio/Audio

You could consider something like:
<Audio src="MYAUDIO_PATH.mp3" :volume="0.3" /> 

As example

### Alternative

Feel free to suggest other alternatives

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.

**Comment by kiri10ten** [comment]
Hello @JaimeTorrealba,please assign this issue to me ,I would like to work on it !

**Comment by JaimeTorrealba** [comment]
Hi @kiri10ten how are you? 
I just come to ask if everything is ok? Can I help you with something? Feel free to ask me directly on discord 

I'm here for help :)
