### ISSUE TITLE
catmullromline 

### ISSUE THREAD

**Issue by JaimeTorrealba** [Tresjs/cientos#222]
### Description

As a developer using Tresjs I would like to add catmullromline components, in shapes

<CatmullRomLine
  points={[[0, 0, 0], ...]}      
  closed={false}                 
  curveType="centripetal"         
  tension={0.5}                  
  color="black"                   
  lineWidth={1}                   
  dashed={false}                  
  vertexColors={[[0, 0, 0], ...]} 
  {...lineProps}                 
  {...materialProps}              
/>

### Suggested solution

Similar to: [catmullromline](https://github.com/pmndrs/drei#catmullromline)

### Alternative

Any other alternative is considered

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.

**Comment by JaimeTorrealba** [comment]
@andretchen0 we could close this issue right?

**Comment by andretchen0** [comment]
> @andretchen0 we could close this issue right?

Yes

For what it's worth, I can close issues, merge, etc., but I prefer to leave those decisions to you guys.

**Comment by JaimeTorrealba** [comment]
They close automatically if we add close "#NUMBER-ISSUE" in the PR :)

**Comment by andretchen0** [comment]
> They close automatically if we add close "#NUMBER-ISSUE" in the PR :)

😀
