### ISSUE TITLE
ContactShadows demo throws error

### ISSUE THREAD

**Issue by andretchen0** [Tresjs/cientos#230]
### Describe the bug

The guide page at:

https://cientos.tresjs.org/guide/staging/contact-shadows.html

throws an error:

```
Uncaught (in promise) TypeError: "position" is read-only
```

This appears related to `ContactShadows` `helper` prop:

* When `true`, the error is thrown. 
* When`false`, the error is not thrown.

### Reproduction

https://stackblitz.com/edit/tresjs-basic-pfyd2g?file=src%2Fcomponents%2FTheExperience.vue

### Steps to reproduce

* Open the [StackBlitz](https://stackblitz.com/edit/tresjs-basic-pfyd2g?file=src%2Fcomponents%2FTheExperience.vue) or open the [guide](https://cientos.tresjs.org/guide/staging/contact-shadows.html).
* Check the browser console.

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 102.31 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.5.1 - /opt/homebrew/bin/node
    npm: 9.8.0 - /opt/homebrew/bin/npm
    pnpm: 8.6.5 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 116.0.5845.187
    Safari: 16.2
  npmPackages:
    @tresjs/core: ^3.2.1 => 3.2.1 
    @tresjs/eslint-config-vue: ^0.1.1 => 0.1.1 
    vite: ^4.4.9 => 4.4.9
```

### Used Package Manager

pnpm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/Tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by andretchen0** [comment]
Additional ContactShadows problems, in `./playground/src/pages/staging/ContactShadowsDemo.vue`

* the shadows disappear when the "resolution" slider is changed in the UI
* the shadow color doesn't change when `state.color` is changed in the UI

For clarity, here's the Leches version of the UI in question:

<img width="307" alt="Screenshot 2023-12-14 at 15 18 37" src="https://github.com/Tresjs/cientos/assets/20469369/0a3d7f83-1cac-4c58-894a-19964df4b087">

**Comment by alvarosabu** [comment]
Hi @andretchen0 I think there are several issues with that component and reactivity, I will take it

**Comment by JaimeTorrealba** [comment]
Should we close this one? @alvarosabu @andretchen0

**Comment by andretchen0** [comment]
Closing. Completed by #449
