### ISSUE TITLE
Cannot start nuxt after update Cientos to 3.4.0

### ISSUE THREAD

**Issue by Dekier** [Tresjs/cientos#236]
### Describe the bug

![image](https://github.com/Tresjs/cientos/assets/30952768/0bb24d3e-cde0-4284-9b0d-f3023ce498d6)

### Reproduction

https://github.com/Dekier/sientos-error

### Used Package Manager

yarn

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/Tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kekkorider** [comment]
Same here.

`3.3.0` works as expected.

**Comment by notarun** [comment]
Updating `cientos` in a vue project fails too. In [vue-tres-starter](https://github.com/kekkorider/vue-tres-starter) updating dependencies fails the build.
Fork: https://github.com/notarun/vue-tres-starter/tree/experiment

**Comment by notarun** [comment]
Fixed with `3.4.1` 🎉
