### ISSUE TITLE
[Html] - problem with dynamic classes (nuxt)

### ISSUE THREAD

**Issue by Dekier** [Tresjs/cientos#251]
### Describe the bug

When I want to use dynamic classes in HTML from cientos, nothing happens.

Component: `Telescope`

### Reproduction

https://github.com/Dekier/html-error

### Steps to reproduce

yarn => yarn dev

### Used Package Manager

yarn

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/Tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by alvarosabu** [comment]
I managed to reproduce it, @Dekier curiously if you resize it updates so it most be a render issue, I will take a look to it
