### ISSUE TITLE
Pass CameraControls helpers through ref

### ISSUE THREAD

**Issue by CptJJ** [Tresjs/cientos#289]
### Description

Expose access to helpers listed here https://github.com/yomotsu/camera-controls to enable easy camera animation. Some seem more useful than others.

### Suggested solution

Would look something like this:
```js
 <CameraControls ref="camcontrols" />
const camcontrols = ref()

watchEffect(() => {
  camcontrols.moveTo(someNumberX.value, someNumberY.value, someNumberZ.value, true)
})
```

**Comment by JaimeTorrealba** [comment]
As we discuss in Discord, with just camControls you're not accessing the object you need to provide a value.value. The end will be something like:

camcontrols.value.value.moveTo(someNumberX.value, someNumberY.value, someNumberZ.value, true)

If this solves your issue, please close this one @CptJJ
