### ISSUE TITLE
Mask component for cientos

### ISSUE THREAD

**Issue by JaimeTorrealba** [Tresjs/cientos#304]
### Description

Mask use the Stencil Buffer to create the illusion of a second scene without the performance of a second render like with the renderTargets.

To illustrate this, you can check: https://youtu.be/X93GxW84t84

### Suggested solution

Could be base on: https://github.com/pmndrs/drei?tab=readme-ov-file#mask

You can check others stencil options directly in the official docs: https://threejs.org/docs/index.html?q=materi#api/en/constants/Materials

But feel free to suggest any other alternative

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.

**Comment by AndreasFaust** [comment]
I created this example using the stencil buffer:
https://stackblitz.com/edit/vitejs-vite-zqtnhb?file=README.md
