### ISSUE TITLE
Precipitation as leaves

### ISSUE THREAD

**Issue by Dekier** [Tresjs/cientos#318]
### Description

I wanted to make falling leaves using Cientos Precipitation but unfortunately it doesn't look very good :/ Snow or rain looks nice, but with leaves it doesn't look realistic. 

### Suggested solution

Maybe add random rotation? Random descent speed? Random scale?
https://www.youtube.com/watch?v=OLEWP7VZVzQ
This example is amazing

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.

**Comment by JaimeTorrealba** [comment]
After investigate this one, the only way is to change to a shader material. But that could potentially break other implementation, so maybe for this one is better a personal implementation, I'll close this one for now
