### ISSUE TITLE
Click to move object with Path

### ISSUE THREAD

**Issue by alvarosabu** [Tresjs/cientos#325]
### Description

As a developer, I would like to have a composable to easily move and object with path via click https://x.com/AndrewChenE/status/1742001427491455213?s=20

### Suggested solution

Dunno yet

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.

**Comment by JaimeTorrealba** [comment]
I believe this deserves a dedicated pkg only focus on the characters controllers
