### ISSUE TITLE
`<StatsGl />` broken in `3.7.0`

### ISSUE THREAD

**Issue by kekkorider** [Tresjs/cientos#336]
### Describe the bug

While upgrading all the packages in my starter I noticed that `<StatsGl />` doesn't work and triggers the following error:

<img width="631" alt="Screenshot 2024-01-23 alle 14 00 02" src="https://github.com/Tresjs/cientos/assets/5191941/72e81644-011b-4bad-8e25-05a0684d789b">

### Reproduction

https://stackblitz.com/github/kekkorider/vue-tres-starter/tree/feat/cientos-3.7.0

### Steps to reproduce

If you remove the `<StatsGl />` component In `src/App.vue` the error is gone.

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1
    Memory: 485.48 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.10.5 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 120.0.6099.234
    Safari: 17.2.1
  npmPackages:
    @tresjs/cientos: ^3.7.0 => 3.7.0 
    @tresjs/core: ^3.6.1 => 3.6.1 
    vite: ^5.0.12 => 5.0.12
```

### Used Package Manager

pnpm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/Tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by JaimeTorrealba** [comment]
Hi, @RenaudRohlinger quick question about this one, debugging a little seems like the problem is that StatsGl his version still uses StatsGl.Container

![image](https://github.com/Tresjs/cientos/assets/63722373/82d0ebce-d91c-4a3f-82c5-d6ffbb4939bf)
That is a photo in my local with all dependencies updated.

In the Cientos Playground works fine with StatsGl.dom. The fix is easy, just check if StatsGl.dom is empty, to use StatsGl.Container.
But I'm curious about why this happened. Do you have any Idea?

**Comment by RenaudRohlinger** [comment]
It's super odd, I just checked the source published on npm and everything points to .dom and there is a fallback available:
```js
  get container() {
    console.warn("Stats: Deprecated! this.container as been replaced to this.dom ");
    return this.dom;
  }
  ```
  
  For example if using the source code from the `pnpm-lock` file in the example:
  [https://registry.npmjs.org/stats-gl/-/stats-gl-2.0.1.tgz](https://registry.npmjs.org/stats-gl/-/stats-gl-2.0.1.tgz)

To be honest I have no idea for the solution except the patch proposed on cientos side.

**Comment by JaimeTorrealba** [comment]
@RenaudRohlinger thanks for answer so fast, and no problem the solution is not difficult.

I just wanted to know why could happen, :) have a nice day
