### ISSUE TITLE
CameraControls not working

### ISSUE THREAD

**Issue by Sea-DH1** [Tresjs/cientos#341]
### Describe the bug

CameraControls not working, Scene cannot be interacted with.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-eg7wqt

### System Info

```shell
system:
    OS: windows
    CPU: (8) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.2GHz
    Memory: 0 Bytes / 0 Bytes
  Binaries:
    Node: 18.18.0
    Yarn: 1.22.19
    npm: 9.4.2
    pnpm: 8.14.0
  npmPackages:
    @tresjs/cientos: 3.7.0 => 3.7.0 
    @tresjs/core: 3.7.0 => 3.7.0 
    vite: ^5.0.12 => 5.0.12
```

### Used Package Manager

npm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/Tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by andretchen0** [comment]
@JaimeTorrealba , I can't get the StackBlitz to run. It's stalling here for me:

<img width="318" alt="Screenshot 2024-02-04 at 20 20 42" src="https://github.com/Tresjs/cientos/assets/20469369/971866be-1fb5-45e5-8881-57eb5139dd2e">

Any luck on your end?

**Comment by JaimeTorrealba** [comment]
Nop I can't...

I'll try tomorrow

**Comment by Sea-DH1** [comment]
Is it a network problem? I tried it and it can be opened

**Comment by andretchen0** [comment]
> Is it a network problem? I tried it and it can be opened

Working now.

**Comment by andretchen0** [comment]
### Expected:

The camera should move when the mouse is click and dragged across the canvas.

### Bug:

Nothing happens (on StackBlitz).

### Further context

* The code in the StackBlitz is taken from [the docs example.](https://cientos.tresjs.org/guide/controls/camera-controls.html#usage) Everything is working fine for me [there.](https://cientos.tresjs.org/guide/controls/camera-controls.html)
* StackBlitz is using current releases of Cientos and Tres.
* `<OrbitControls />` works fine when imported and put in the place of `<CameraControls ...>`.
* I cannot reproduce the bug when running the example code in a local playground.

Fwiw, here's another [StackBlitz](https://stackblitz.com/edit/vitejs-vite-8mpdea?file=src%2FApp.vue) without `style.css` and `assets`, without additional components, and with all Tres code in `app.vue`. The problem continues for me, but only on StackBlitz.

@Sea-DH1 . Can you reproduce the bug locally or anywhere else but StackBlitz?
@JaimeTorrealba . Any ideas?

**Comment by Sea-DH1** [comment]
@andretchen0 @JaimeTorrealba 
The code is copied from the document CameraControls, nothing has changed.

**Comment by Sea-DH1** [comment]
@JaimeTorrealba 
I directly copied the code you linked above, but it’s still the same, the camera can’t rotate.

**Comment by Sea-DH1** [comment]
@andretchen0 
This link
https://stackblitz.com/edit/vitejs-vite-28xfvq?file=src%2FApp.vue

**Comment by Sea-DH1** [comment]
@JaimeTorrealba 
Hi, may I ask which version of cientos is used in your case? I copied my code and it ran normally.

**Comment by Sea-DH1** [comment]
@JaimeTorrealba 
Wow, yes, I updated to version 3.8.0 and it works normally
