### ISSUE TITLE
New linter rules erase some JSDoc formatting

### ISSUE THREAD

**Issue by andretchen0** [Tresjs/cientos#398]
## Problem

A linter rule added in #388 erases valid Markdown. 

### Italics

This is an [italicized word in valid Markdown](https://www.markdownguide.org/basic-syntax/#italic) in a JSDoc. 

```
/**
 * *italic*
 **/
```

<img width="150" alt="Screenshot 2024-05-02 at 23 01 10" src="https://github.com/Tresjs/cientos/assets/20469369/64a46a9a-1793-4a2d-aa4e-8f324d4d5388">

Linted:

```
/**
 * italic*
 **/
```

<img width="148" alt="Screenshot 2024-05-02 at 23 02 12" src="https://github.com/Tresjs/cientos/assets/20469369/44f66638-083c-4bc3-b16d-e1bd8b0f7456">

### Bulleted lists

This is a [bulleted list in valid Markdown](https://www.markdownguide.org/basic-syntax/#unordered-lists) in a JSDoc.

```
/**
 * * list item 1
 * * list item 2
 * * list item 3
 **/
```

<img width="119" alt="Screenshot 2024-05-02 at 23 03 16" src="https://github.com/Tresjs/cientos/assets/20469369/cf257066-50f7-4d26-96ab-ab91cfa3a9f4">

Linted:

```
/**
 * list item 1
 * list item 2
 * list item 3
 **/
```

<img width="188" alt="Screenshot 2024-05-02 at 23 03 50" src="https://github.com/Tresjs/cientos/assets/20469369/55ceb768-3c85-43c5-b737-4ad173d3011a">

## Solution

* [Change this setting](https://github.com/gajus/eslint-plugin-jsdoc/blob/e343ab5b1efaa59b07c600138aee070b4083857e/docs/rules/no-multi-asterisks.md?plain=1#L254): `"jsdoc/no-multi-asterisks": ["error"|"warn", {"allowWhitespace":true}]` 
* Revert the incorrectly linted changes.

## See also

* https://github.com/gajus/eslint-plugin-jsdoc/issues/773
* https://github.com/gajus/eslint-plugin-jsdoc/issues/803

## Steps to reproduce

* Add this to a Cientos component:

```
/**
 * * list item 1
 * * list item 2
 * * list item 3
 **/
interface List {}
```

* Save
* Run `pnpm run lint --fix`
* The result will be:

```
/**
 * list item 1
 * list item 2
 * list item 3
 **/
interface List {}
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/Tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by alvarosabu** [comment]
Hi @andretchen0 thanks for raising this, we could change this setting directly on https://github.com/Tresjs/eslint-config wdyt?

**Comment by andretchen0** [comment]
> Hi @andretchen0 thanks for raising this, we could change this setting directly on https://github.com/Tresjs/eslint-config so the whole ecosystem is protected against the issue, wdyt?

Sounds good.

**Comment by JaimeTorrealba** [comment]
I'll close this one, feel free to re-open if the problem still persist
