### ISSUE TITLE
KeyboardControls not working in Nuxt 3.11.2

### ISSUE THREAD

**Issue by JakobHock** [Tresjs/cientos#403]
### Describe the bug

KeyboardControls as per documentation are currently not working with Nuxt 3.11.2.

### Reproduction

https://stackblitz.com/edit/nuxt-starter-cpvwvw?file=app.vue

### Steps to reproduce

1. Click on canvas
2. Try to move
3. Camera not moving

### System Info

```shell
OS: Windows 10 10.0.19045
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 2.31 GB / 15.95 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.0.6 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Chrome: 124.0.6367.119
    Edge: Chromium (123.0.2420.81)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    @tresjs/cientos: ^3.8.0 => 3.8.0
    @tresjs/nuxt: ^2.1.1 => 2.1.1
```

### Used Package Manager

pnpm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/Tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by JaimeTorrealba** [comment]
This is weird, but in the V4 of cientos (soon) the KeyboardControls will be modified, and comes with breaking changes.

Maybe try this instead: https://github.com/JaimeTorrealba/tres-fps-controls

**Comment by JakobHock** [comment]
Thank you very much.
I will take a look at it 👍

**Comment by janvorisek** [comment]
`CameraControls` don't work in the same way. The are added with no error, accessible using ref, yet no action on mousewheel/drag.
