### ISSUE TITLE
Linter is breaking some props

### ISSUE THREAD

**Issue by andretchen0** [Tresjs/cientos#411]
### Describe the bug

It appears the new linter is breaking some props:

* `<Sky/>`: https://github.com/Tresjs/cientos/commit/4999bb1dea4c902ad5b19dd5982a2e9537d84bc8#diff-bcb1b58e8e953711ce44278df539b7606cdffdceb65be40747ab67c97e79672e
* `<HolographicMaterial />`: https://github.com/Tresjs/cientos/commit/4999bb1dea4c902ad5b19dd5982a2e9537d84bc8#diff-9ca529b6b05acda73f50d969d3f1cd689a49b87118f7126bf5ac523277ed42d9

### Reproduction

N/A

### Steps to reproduce

See the links in the description. They show the `git blame` where the props changed.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/Tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by alvarosabu** [comment]
Hi!, we should add the exception for the rule that is breaking here: https://github.com/Tresjs/eslint-config, or locally by overriding the rules

**Comment by JaimeTorrealba** [comment]
I think this is completed, right? Feel free to re-open if not
