### ISSUE TITLE
Lensflare playground demo is broken

### ISSUE THREAD

**Issue by alvarosabu** [Tresjs/cientos#435]
### Describe the bug

Lensflare seems to be broken on v4

Cannot destructure property 'registerCamera' of '(intermediate value)(intermediate value)(intermediate value)' as it is undefined.

![Screenshot 2024-06-05 at 17 25 43](https://github.com/Tresjs/cientos/assets/4699008/7431be77-76f4-41ee-aa41-b0ceb5bf4c5e)

### Reproduction

Run local playground

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1 Pro
    Memory: 51.02 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    pnpm: 8.15.4 - ~/Library/pnpm/pnpm
    bun: 1.0.2 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 120.1.61.116
    Chrome: 125.0.6422.142
    Safari: 17.5
  npmPackages:
    @tresjs/core: 4.0.0-rc.2 => 4.0.0-rc.2 
    @tresjs/leches: ^0.14.0 => 0.14.0
```

### Used Package Manager

pnpm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/Tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by andretchen0** [comment]
I think this is a problem with `nodeOps` in the core:

```ts
      const { registerCamera } = child?.__tres?.root as TresContext;
```

The optional chaining (`?`) signals that one might expect `undefined` is sometimes returned. `undefined` can't be destructured:

```ts
$ node
> { foo } = undefined
Uncaught TypeError: Cannot destructure property 'foo' of 'undefined' as it is undefined.
```

On the team Discord, @garrlker and I were just briefly talking about passing in `context` in order to factor out some of this optional chaining and long lookups.

I'll go ahead and open a PR for that refactor today. It should fix this issue.

**Comment by andretchen0** [comment]
There wasn't a camera in the demo and that made `v4` nodeOps throw.

It'd be great if we always had a dummy camera.

**Comment by JaimeTorrealba** [comment]
I'll close this one, if this is not complete please feel free to re-open @andretchen0
