### ISSUE TITLE
`<Cylinder />`

### ISSUE THREAD

**Issue by andretchen0** [Tresjs/cientos#437]
### Description

As a developer using Tres, I would like to have a `<Cylinder />` component in order to easily add a customizable cylinder to scenes.

### Suggested solution

Implement a Cientos component with an underlying `THREE.CylinderGeometry` and accepting the props of the same, with the same defaults.

https://threejs.org/docs/#api/en/geometries/CylinderGeometry

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.

**Comment by JakobHock** [comment]
Will create a PR for this
