### ISSUE TITLE
<Sky />    can not utilize

### ISSUE THREAD

**Issue by IKE1001** [Tresjs/cientos#451]
### Describe the bug

![image](https://github.com/user-attachments/assets/fc2cac54-b79e-4699-842f-b0c0dae20366)
<script setup lang="ts">
import { TresCanvas } from '@tresjs/core'
import { OrbitControls, Sky } from '@tresjs/cientos'
</script>

<template>
  <TresCanvas :tone-mapping-exposure="0.25">
    <TresPerspectiveCamera :position="[0, 0, 2000]" />
    <Sky />
    <OrbitControls
      :enable-pan="false"
      :enable-zoom="false"
    />
  </TresCanvas>
</template>

### Reproduction

no

### Used Package Manager

npm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by RaneeX** [comment]
Instead of importing from cientos, you can use the Sky component in this way below, and I don't see why using the import is not available.

Code from cientos:
```vue
<script setup lang="ts">
// eslint-disable-file vue/attribute-hyphenation
import { MathUtils, Vector3 } from 'three';
import { Sky as SkyImpl } from 'three/examples/jsm/objects/Sky';
import { computed, shallowRef } from 'vue';

export interface SkyProps {
  /**
   * Haziness
   * @param {number} turbidity
   */
  turbidity?: number;
  /**
   * [Rayleigh scattering](https://en.wikipedia.org/wiki/Rayleigh_scattering)
   */
  rayleigh?: number;
  /**
   * [Mie scattering](https://en.wikipedia.org/wiki/Mie_scattering) amount
   */
  mieCoefficient?: number;
  /**
   * [Mie scattering](https://en.wikipedia.org/wiki/Mie_scattering) direction
   */
  mieDirectionalG?: number;
  /**
   * Sun's elevation from the horizon, in degrees
   */
  elevation?: number;
  /**
   * Sun's [azimuth angle](https://en.wikipedia.org/wiki/Solar_azimuth_angle), in degrees – its horizontal coordinate on the horizon
   */
  azimuth?: number;
  /**
   * Sky box scale
   */
  distance?: number;
}

const props = withDefaults(defineProps<SkyProps>(), {
  turbidity: 3.4,
  rayleigh: 3,
  mieCoefficient: 0.005,
  mieDirectionalG: 0.7,
  elevation: 0.6,
  azimuth: 180,
  distance: 450000,
});

const skyRef = shallowRef<SkyImpl>();
const skyImpl = new SkyImpl();
const sunPosition = computed(() => getSunPosition(props.azimuth, props.elevation));

function getSunPosition(azimuth: number, elevation: number) {
  const phi = MathUtils.degToRad(90 - elevation);
  const theta = MathUtils.degToRad(azimuth);
  return new Vector3().setFromSphericalCoords(1, phi, theta);
}

defineExpose({
  root: skyRef,
  sunPosition: sunPosition.value,
});
</script>

<template>
  <primitive
    ref="skyRef"
    :object="skyImpl"
    :material-uniforms-turbidity-value="props.turbidity"
    :material-uniforms-rayleigh-value="props.rayleigh"
    :material-uniforms-mieCoefficient-value="props.mieCoefficient"
    :material-uniforms-mieDirectionalG-value="props.mieDirectionalG"
    :material-uniforms-sunPosition-value="sunPosition"
    :scale="props.distance"
  />
</template>

```

**Comment by Ferrarii-430** [comment]
I also encountered this problem，But it's normal in the guidelines
Suggest adding version display in the guidelines

**Comment by andretchen0** [comment]
Hi @IKE1001 

Thanks for filing the issue. I can also reproduce.

## Minimal reproduction

https://stackblitz.com/edit/tresjs-basic-2wnmw7?file=src%2Fcomponents%2FTheExperience.vue

## Workaround

@RaneeX 's solution here: https://github.com/Tresjs/cientos/issues/451#issuecomment-2277028362

## For followup

In the past, Tres core as well as the linter have broken props that have `camelCase` in their props, which Cientos sometimes uses for sending values directly to THREE. 

That may be what's happening here with: `:material-uniforms-mieCoefficient-value`.

**Comment by JaimeTorrealba** [comment]
This was solved with the V4 of cientos, please feel free to re-open if not
