### ISSUE TITLE
Smooth Orbit Controls

### ISSUE THREAD

**Issue by LucaArgentieri** [Tresjs/cientos#495]
### Description

As a dev using TresJS, I would like to have smooth OrbitControls and TrackballControls

### Suggested solution

https://twitter.com/niccolofanton/status/1836727821005139988
https://github.com/niccolofanton/SmoothOrbitControls

Credits @niccolofanton

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.

**Comment by JaimeTorrealba** [comment]
Hi, what is the difference or benefits between CameraControls and smoothOrbitControls?
