### ISSUE TITLE
Mesh Reflector Material 

### ISSUE THREAD

**Issue by alvarosabu** [Tresjs/cientos#5]
**Is your feature request related to a problem? Please describe.**
Shining floors everywhere!!

**Describe the solution you'd like**
Same concept as R3F Drei https://github.com/pmndrs/drei#meshreflectormaterial 

**Suggested solution**
Shaders

**Comment by JaimeTorrealba** [comment]
Hi @alvarosabu :)
What is missing from this, any reason why is not in the docs?

![image](https://github.com/Tresjs/cientos/assets/63722373/87c8ffe9-e133-497c-adab-8cc1f1317c36)

**Comment by JaimeTorrealba** [comment]
I'm going to close this one, since @andretchen0 is working on this one in another issue

**Comment by andretchen0** [comment]
Hey @JaimeTorrealba !

Yeah, the new version will replace this version. So all good to close here, I think.

@alvarosabu agreed with that approach when I asked him a few days ago on the Discord.
